# Generated by Django 4.2.1 on 2023-05-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dailywaste'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('complaint', models.CharField(max_length=200)),
            ],
        ),
    ]
