# Generated by Django 4.2.1 on 2023-05-28 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_complaint_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driversignup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='DriverMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.complaint_register')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.driversignup')),
            ],
        ),
    ]
