# Generated by Django 4.2.1 on 2023-06-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_complaint_register_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=50)),
                ('complaint', models.TextField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
