# Generated by Django 4.2.1 on 2023-06-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='complaint',
        ),
    ]
